<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="pennant-vsp121" failures="1" tests="10" name="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" time="0.650" errors="0" timestamp="2023-07-03T15:13:40 IST" skipped="0">
  <testcase classname="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" name="testGetAccountsappByType" time="0.003"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" name="testSaveAccountdocument" time="0.002"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" name="testMergeAccount" time="0.002"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" name="testGetAccountApplicationById" time="0.015"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" name="testSaveAccount" time="0.002"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" name="testGetAccountById" time="0.566"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" name="testGetAll" time="0.003"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" name="testSaveTheAccountapp" time="0.010">
    <failure message="
Wanted but not invoked:
entityManager.persist(
    com.nkxgen.spring.jdbc.model.AccountApplication@11653e3b
);
-&gt; at com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest.testSaveTheAccountapp(AccountApplicationDAOTest.java:156)

However, there was exactly 1 interaction with this mock:
entityManager.merge(
    com.nkxgen.spring.jdbc.model.AccountApplication@48bfb884
);
-&gt; at com.nkxgen.spring.jdbc.Dao.AccountApplicationDAO.savetheAccountapp(AccountApplicationDAO.java:148)

" type="org.mockito.exceptions.verification.WantedButNotInvoked">
      <![CDATA[Wanted but not invoked:
entityManager.persist(
    com.nkxgen.spring.jdbc.model.AccountApplication@11653e3b
);
-> at com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest.testSaveTheAccountapp(AccountApplicationDAOTest.java:156)

However, there was exactly 1 interaction with this mock:
entityManager.merge(
    com.nkxgen.spring.jdbc.model.AccountApplication@48bfb884
);
-> at com.nkxgen.spring.jdbc.Dao.AccountApplicationDAO.savetheAccountapp(AccountApplicationDAO.java:148)


at com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest.testSaveTheAccountapp(AccountApplicationDAOTest.java:156)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testSaveTheAccountapp -->
  <testcase classname="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" name="testSave" time="0.001"/>
  <testcase classname="com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest" name="testGetAccountsByType" time="0.046"/>
</testsuite> <!-- com.nkxgen.spring.jdbc.Test.AccountApplicationDAOTest -->
